In [2]:
import pandas as pd

In [3]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Amit", "Rahul", "Priya", "Neha", "Vikram"],
    "age": [25, 32, 28, 35, 24],
    "city": ["Mumbai", "Pune", "Mumbai", "Delhi", "Pune"],
    "salary": [50000, 75000, 65000, 90000, 45000]
})

print(df)

     name  age    city  salary
0    Amit   25  Mumbai   50000
1   Rahul   32    Pune   75000
2   Priya   28  Mumbai   65000
3    Neha   35   Delhi   90000
4  Vikram   24    Pune   45000

In [11]:
df[["name"]]

     name
0    Amit
1   Rahul
2   Priya
3    Neha
4  Vikram

In [5]:
df[df["age"] > 30]

    name  age   city  salary
1  Rahul   32   Pune   75000
3   Neha   35  Delhi   90000

In [6]:
df["age"] > 30

0    False
1     True
2    False
3     True
4    False
Name: age, dtype: bool

In [7]:

df[(df["age"] > 25) & (df["salary"] > 60000)]

    name  age    city  salary
1  Rahul   32    Pune   75000
2  Priya   28  Mumbai   65000
3   Neha   35   Delhi   90000

In [12]:
df[["name"]]

     name
0    Amit
1   Rahul
2   Priya
3    Neha
4  Vikram

In [13]:
df[["name","salary"]]

     name  salary
0    Amit   50000
1   Rahul   75000
2   Priya   65000
3    Neha   90000
4  Vikram   45000

In [15]:
df[df["salary"]>60000]

    name  age    city  salary
1  Rahul   32    Pune   75000
2  Priya   28  Mumbai   65000
3   Neha   35   Delhi   90000

In [19]:
df[df["city"] == "Mumbai"]

    name  age    city  salary
0   Amit   25  Mumbai   50000
2  Priya   28  Mumbai   65000

In [20]:
df[ (df["salary"] > 60000) & (df["age"] > 25) ]

    name  age    city  salary
1  Rahul   32    Pune   75000
2  Priya   28  Mumbai   65000
3   Neha   35   Delhi   90000

In [22]:
df[ (df["city"] == "Mumbai") | (df["city"] == "Pune") ]

     name  age    city  salary
0    Amit   25  Mumbai   50000
1   Rahul   32    Pune   75000
2   Priya   28  Mumbai   65000
4  Vikram   24    Pune   45000

In [24]:
df[df["age"].between(25 ,32)]

    name  age    city  salary
0   Amit   25  Mumbai   50000
1  Rahul   32    Pune   75000
2  Priya   28  Mumbai   65000

In [30]:
df.loc[df["salary"] > 60000 , ["name" , "salary"]]

    name  salary
1  Rahul   75000
2  Priya   65000
3   Neha   90000

In [32]:
df.iloc[ : 3 , : 3]

    name  age    city
0   Amit   25  Mumbai
1  Rahul   32    Pune
2  Priya   28  Mumbai

In [33]:
df.loc[0, "age"]

np.int64(25)

In [34]:
df.iloc[0, 1]

np.int64(25)

In [38]:
df[ (df["city"].isin(["Mumbai" , "Pune"])) & (df["salary"] > 50000) ]

    name  age    city  salary
1  Rahul   32    Pune   75000
2  Priya   28  Mumbai   65000