In [1]:
import pandas as pd

In [48]:
import numpy as np

In [35]:


df = pd.DataFrame({
    "name": ["Amit", "Rahul", "Priya", "Neha", "Vikram"],
    "age": [25, 32, 28, 35, 24],
    "salary": [50000, 75000, 65000, 90000, 45000],
    "department": ["IT", "Finance", "IT", "HR", "Finance"]
})

df

     name  age  salary department
0    Amit   25   50000         IT
1   Rahul   32   75000    Finance
2   Priya   28   65000         IT
3    Neha   35   90000         HR
4  Vikram   24   45000    Finance

In [36]:
df["bonus"] = df["salary"] * 0.15

In [37]:
df["total_salary"] = df["salary"] + df["bonus"]

In [38]:
df

     name  age  salary department    bonus  total_salary
0    Amit   25   50000         IT   7500.0       57500.0
1   Rahul   32   75000    Finance  11250.0       86250.0
2   Priya   28   65000         IT   9750.0       74750.0
3    Neha   35   90000         HR  13500.0      103500.0
4  Vikram   24   45000    Finance   6750.0       51750.0

In [39]:
df["salary_level"] = df["salary"].apply(
    lambda x: "High" if x >= 70000 else "Normal"
)

In [40]:
df

     name  age  salary department    bonus  total_salary salary_level
0    Amit   25   50000         IT   7500.0       57500.0       Normal
1   Rahul   32   75000    Finance  11250.0       86250.0         High
2   Priya   28   65000         IT   9750.0       74750.0       Normal
3    Neha   35   90000         HR  13500.0      103500.0         High
4  Vikram   24   45000    Finance   6750.0       51750.0       Normal

In [41]:
department_codes = {
    "IT": "I",
    "Finance": "F",
    "HR": "H"
}
df["department_codes"] = df["department"].map(department_codes)

In [42]:
df

,name,age,salary,department,bonus,total_salary,salary_level,department_codes
0,Amit,25,50000,IT,7500.0,57500.0,Normal,I
1,Rahul,32,75000,Finance,11250.0,86250.0,High,F
2,Priya,28,65000,IT,9750.0,74750.0,Normal,I
3,Neha,35,90000,HR,13500.0,103500.0,High,H
4,Vikram,24,45000,Finance,6750.0,51750.0,Normal,F

In [43]:
df["age_group"] = df["age"].apply(
    lambda age: "Young" if age < 30 else "30+"
)

In [44]:
df

,name,age,salary,department,bonus,total_salary,salary_level,department_codes,age_group
0,Amit,25,50000,IT,7500.0,57500.0,Normal,I,Young
1,Rahul,32,75000,Finance,11250.0,86250.0,High,F,30+
2,Priya,28,65000,IT,9750.0,74750.0,Normal,I,Young
3,Neha,35,90000,HR,13500.0,103500.0,High,H,30+
4,Vikram,24,45000,Finance,6750.0,51750.0,Normal,F,Young

In [45]:
df

,name,age,salary,department,bonus,total_salary,salary_level,department_codes,age_group
0,Amit,25,50000,IT,7500.0,57500.0,Normal,I,Young
1,Rahul,32,75000,Finance,11250.0,86250.0,High,F,30+
2,Priya,28,65000,IT,9750.0,74750.0,Normal,I,Young
3,Neha,35,90000,HR,13500.0,103500.0,High,H,30+
4,Vikram,24,45000,Finance,6750.0,51750.0,Normal,F,Young

In [46]:
conditions = [
    df["salary"] < 50000,
    df["salary"].between(50000, 69999),
    df["salary"] >= 70000
]

choices = [
    "Low",
    "Medium",
    "High"
]

In [49]:
df["salary_level"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

In [50]:
df

,name,age,salary,department,bonus,total_salary,salary_level,department_codes,age_group
0,Amit,25,50000,IT,7500.0,57500.0,Medium,I,Young
1,Rahul,32,75000,Finance,11250.0,86250.0,High,F,30+
2,Priya,28,65000,IT,9750.0,74750.0,Medium,I,Young
3,Neha,35,90000,HR,13500.0,103500.0,High,H,30+
4,Vikram,24,45000,Finance,6750.0,51750.0,Low,F,Young