In [1]:
import pandas as pd

data = {
    "name": ["Amit", "Rahul", "Priya"],
    "age": [25, 30, 28],
    "salary": [50000, 70000, 65000]
}

df = pd.DataFrame(data)

print(df)

    name  age  salary
0   Amit   25   50000
1  Rahul   30   70000
2  Priya   28   65000

In [4]:
df

    name  age  salary
0   Amit   25   50000
1  Rahul   30   70000
2  Priya   28   65000

In [12]:
data = {
    "product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "price": [60000, 1000, 2500, 15000],
    "stock": [10, 50, 30, 15]
}
gf = pd.DataFrame(data)

In [13]:
gf

    product  price  stock
0    Laptop  60000     10
1     Mouse   1000     50
2  Keyboard   2500     30
3   Monitor  15000     15

In [21]:
data = [
     ["Laptop", "Mouse", "Keyboard", "Monitor"],
     [60000, 1000, 2500, 15000],
     [10, 50, 30, 15]
    ]
df = pd.DataFrame(data , columns = ["Model" , "Price" , "stock" , "jato"])

In [23]:
df

    Model  Price     stock     jato
0  Laptop  Mouse  Keyboard  Monitor
1   60000   1000      2500    15000
2      10     50        30       15

In [26]:
data = [
    { "symbol" : "AAPL" , "price" : 220 } ,
{ "symbol" : "MSFT" , "price" : 510 },
 {"symbol" : "NVDA" , "price" : 180 },
 {"symbol" : "GOOGle" , "price" : 190 }
]
df = pd.DataFrame(data)

In [27]:
df

   symbol  price
0    AAPL    220
1    MSFT    510
2    NVDA    180
3  GOOGle    190

In [28]:
import numpy as np

In [29]:
data = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

In [30]:
data

array([[10, 20],
       [30, 40],
       [50, 60]])

In [32]:
df = pd.DataFrame(
    data , columns = ["age" , "salary" ] )

In [33]:
df

   age  salary
0   10      20
1   30      40
2   50      60

In [38]:
data = { 
    "name" : ["Amit" , "Rahul" , "Priya" ],
    "age" : [21 ,22 ,23] 
}
df = pd.DataFrame(data , index = ["student_1" , "student_2" , "student_3"])

In [39]:
df

            name  age
student_1   Amit   21
student_2  Rahul   22
student_3  Priya   23