In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "name": ["Amit", "Rahul", "Priya", "Amit", "Neha"],
    "age": [25, None, 28, 25, 35],
    "salary": [50000, 70000, None, 50000, 90000],
    "city": ["Mumbai", "Pune", "Mumbai", "Mumbai", None]
})

In [4]:
df.isna()

    name    age  salary   city
0  False  False   False  False
1  False   True   False  False
2  False  False    True  False
3  False  False   False  False
4  False  False   False   True

In [5]:
df.isna().sum()

name      0
age       1
salary    1
city      1
dtype: int64

In [6]:
df.isna().any()

name      False
age        True
salary     True
city       True
dtype: bool

In [7]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [9]:
df.duplicated().sum()

np.int64(1)

In [10]:
df.drop_duplicates()

    name   age   salary    city
0   Amit  25.0  50000.0  Mumbai
1  Rahul   NaN  70000.0    Pune
2  Priya  28.0      NaN  Mumbai
4   Neha  35.0  90000.0     NaN

In [11]:
df["city"] = df["city"].fillna("unknown")

In [12]:
df

    name   age   salary     city
0   Amit  25.0  50000.0   Mumbai
1  Rahul   NaN  70000.0     Pune
2  Priya  28.0      NaN   Mumbai
3   Amit  25.0  50000.0   Mumbai
4   Neha  35.0  90000.0  unknown

In [13]:
df["salary"] = df["salary"].fillna(df["salary"].median())

In [14]:
df

    name   age   salary     city
0   Amit  25.0  50000.0   Mumbai
1  Rahul   NaN  70000.0     Pune
2  Priya  28.0  60000.0   Mumbai
3   Amit  25.0  50000.0   Mumbai
4   Neha  35.0  90000.0  unknown

In [15]:
df["age"] = df["age"].astype("Int64")

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     4 non-null      Int64
 2   salary  5 non-null      float64
 3   city    5 non-null      str
dtypes: Int64(1), float64(1), str(2)
memory usage: 348.0 bytes

In [18]:
pd.to_numeric(
    df["salary"],
    errors = "coerce"
)

0    50000.0
1    70000.0
2    60000.0
3    50000.0
4    90000.0
Name: salary, dtype: float64