In [2]:
import pandas as pd

In [3]:
s = pd.Series([10, 20, 30, 40])

In [4]:
s

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
type(s)

pandas.Series

In [6]:
df = pd.DataFrame({
    "name": ["Amit", "Rahul", "Priya"],
    "age": [25, 30, 28],
    "salary": [50000, 70000, 65000]
})

In [7]:
df.shape

(3, 3)

In [8]:
df.columns

Index(['name', 'age', 'salary'], dtype='str')

In [9]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [11]:
df.head()

    name  age  salary
0   Amit   25   50000
1  Rahul   30   70000
2  Priya   28   65000

In [12]:
df.head(1)

   name  age  salary
0  Amit   25   50000

In [13]:
df.tail()

    name  age  salary
0   Amit   25   50000
1  Rahul   30   70000
2  Priya   28   65000

In [14]:
df.tail(1)

    name  age  salary
2  Priya   28   65000

In [15]:
df.sample()

   name  age  salary
0  Amit   25   50000

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
 2   salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 218.0 bytes

In [17]:
df.describe()

             age        salary
count   3.000000      3.000000
mean   27.666667  61666.666667
std     2.516611  10408.329997
min    25.000000  50000.000000
25%    26.500000  57500.000000
50%    28.000000  65000.000000
75%    29.000000  67500.000000
max    30.000000  70000.000000

In [18]:

data = {
    "name": ["Amit", "Rahul", "Priya", "Neha"],
    "age": [25, 30, 28, 35],
    "salary": [50000, 70000, 65000, 90000],
    "department": ["IT", "Finance", "IT", "HR"]
}

df = pd.DataFrame(data)

In [19]:
df

    name  age  salary department
0   Amit   25   50000         IT
1  Rahul   30   70000    Finance
2  Priya   28   65000         IT
3   Neha   35   90000         HR

In [21]:
df.shape

(4, 4)

In [22]:
df.columns

Index(['name', 'age', 'salary', 'department'], dtype='str')

In [25]:
df.dtypes

name            str
age           int64
salary        int64
department      str
dtype: object

In [26]:
df.head(2)

    name  age  salary department
0   Amit   25   50000         IT
1  Rahul   30   70000    Finance

In [27]:
df.tail(2)

    name  age  salary department
2  Priya   28   65000         IT
3   Neha   35   90000         HR

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      str
 1   age         4 non-null      int64
 2   salary      4 non-null      int64
 3   department  4 non-null      str
dtypes: int64(2), str(2)
memory usage: 291.0 bytes

In [29]:
df.describe()

             age        salary
count   4.000000      4.000000
mean   29.500000  68750.000000
std     4.203173  16520.189668
min    25.000000  50000.000000
25%    27.250000  61250.000000
50%    29.000000  67500.000000
75%    31.250000  75000.000000
max    35.000000  90000.000000

In [35]:
df[["name"]]

    name
0   Amit
1  Rahul
2  Priya
3   Neha

In [36]:
data = {
    "Amit": 21,
    "Rahul": 25,
    "Priya": 30
}

ages = pd.Series(data)

In [37]:
ages

Amit     21
Rahul    25
Priya    30
dtype: int64

In [38]:
ages * 2

Amit     42
Rahul    50
Priya    60
dtype: int64

In [39]:
ages // 3

Amit      7
Rahul     8
Priya    10
dtype: int64

In [41]:
ages.mean

<bound method Series.mean of Amit     21
Rahul    25
Priya    30
dtype: int64>

In [42]:
ages.sum

<bound method Series.sum of Amit     21
Rahul    25
Priya    30
dtype: int64>

In [43]:
ages.median

<bound method Series.median of Amit     21
Rahul    25
Priya    30
dtype: int64>

In [44]:
data = {
    "name": ["Amit", "Rahul", "Priya"],
    "age": [25, 30, 28],
    "salary": [50000, 70000, 65000]
}

df = pd.DataFrame(data)

In [46]:
df["age"] + 2

0    27
1    32
2    30
Name: age, dtype: int64

In [47]:
df

    name  age  salary
0   Amit   25   50000
1  Rahul   30   70000
2  Priya   28   65000

In [54]:
df

    name  age  salary  Bonus  Total_salary  (2, Bonus)
0   Amit   25   50000   1000         51000        1000
1  Rahul   30   70000   1200         71200        1200
2  Priya   28   65000    900         65900         900

In [50]:
df["Total_salary"] = df["salary"] + df["Bonus"]

In [51]:
df

    name  age  salary  Bonus  Total_salary
0   Amit   25   50000   1000         51000
1  Rahul   30   70000   1200         71200
2  Priya   28   65000    900         65900

In [57]:
df.drop("Bonus" , axis = 1 )

    name  age  salary  Total_salary  (2, Bonus)
0   Amit   25   50000         51000        1000
1  Rahul   30   70000         71200        1200
2  Priya   28   65000         65900         900

In [59]:
df.drop((2 ,"Bonus") , axis = 1 )

    name  age  salary  Bonus  Total_salary
0   Amit   25   50000   1000         51000
1  Rahul   30   70000   1200         71200
2  Priya   28   65000    900         65900

In [61]:
df

    name  age  salary  Bonus  Total_salary  (2, Bonus)
0   Amit   25   50000   1000         51000        1000
1  Rahul   30   70000   1200         71200        1200
2  Priya   28   65000    900         65900         900

In [63]:
df.drop((2,"Bonus"), axis=1, inplace=True)

In [64]:
df

    name  age  salary  Bonus  Total_salary
0   Amit   25   50000   1000         51000
1  Rahul   30   70000   1200         71200
2  Priya   28   65000    900         65900

In [66]:
scores = pd.Series(
    [85, 92, 78, 96],
    index=["Amit", "Rahul", "Priya", "Neha"]
)

In [67]:
scores

Amit     85
Rahul    92
Priya    78
Neha     96
dtype: int64

In [69]:
sc = scores

In [70]:
sc

Amit     85
Rahul    92
Priya    78
Neha     96
dtype: int64

In [71]:
sc.mean()

np.float64(87.75)

In [72]:
sc.median()

np.float64(88.5)

In [74]:
sc.max()

np.int64(96)

In [75]:
sc.min()

np.int64(78)

In [76]:
data = {
    "name": ["A", "B", "C", "D"],
    "math": [80, 90, 70, 95],
    "science": [85, 88, 75, 92]
}
gf = pd.DataFrame(data)

In [77]:
gf

  name  math  science
0    A    80       85
1    B    90       88
2    C    70       75
3    D    95       92

In [79]:
gf["total"] = gf["math"] + gf["science"]

In [80]:
gf

  name  math  science  total
0    A    80       85    165
1    B    90       88    178
2    C    70       75    145
3    D    95       92    187

In [85]:
gf["average"] = gf["total"] // 2

In [86]:
gf

  name  math  science  total  average
0    A    80       85    165       82
1    B    90       88    178       89
2    C    70       75    145       72
3    D    95       92    187       93

In [93]:
gf["total"].max

<bound method Series.max of 0    A
1    B
2    C
3    D
Name: name, dtype: str>

In [88]:
s1 = pd.Series([10, 20, 30], index=["A", "B", "C"])
s2 = pd.Series([5, 10, 15], index=["B", "C", "D"])

print(s1 + s2)

A     NaN
B    25.0
C    40.0
D     NaN
dtype: float64