In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "name": ["Amit", "Rahul", "Priya", "Neha", "Vikram"],
    "age": [25, 32, 28, 35, 24],
    "salary": [50000, 75000, 65000, 90000, 45000],
    "department": ["IT", "Finance", "IT", "HR", "Finance"]
})

In [3]:
df

     name  age  salary department
0    Amit   25   50000         IT
1   Rahul   32   75000    Finance
2   Priya   28   65000         IT
3    Neha   35   90000         HR
4  Vikram   24   45000    Finance

In [4]:
df["bonus"] = df["salary"] * 0.10
print(df)

     name  age  salary department   bonus
0    Amit   25   50000         IT  5000.0
1   Rahul   32   75000    Finance  7500.0
2   Priya   28   65000         IT  6500.0
3    Neha   35   90000         HR  9000.0
4  Vikram   24   45000    Finance  4500.0

In [5]:
df["total_salary"] = df["salary"] + df["bonus"]

In [8]:
df["age_group"] = df["age"].apply(
    lambda x: "30+" if x > 30 else "young")

In [9]:
df

     name  age  salary department   bonus  total_salary age_group
0    Amit   25   50000         IT  5000.0       55000.0     young
1   Rahul   32   75000    Finance  7500.0       82500.0       30+
2   Priya   28   65000         IT  6500.0       71500.0     young
3    Neha   35   90000         HR  9000.0       99000.0       30+
4  Vikram   24   45000    Finance  4500.0       49500.0     young

In [21]:
df["department_full"] = {
"IT":"Technology",
"Finance": "Finance",
"HR":"Human Resources"}

In [27]:
df

,name,age,salary,department,bonus,total_salary,age_group,department_full
0,Amit,25,50000,IT,5000.0,55000.0,young,NaN
1,Rahul,32,75000,Finance,7500.0,82500.0,30+,NaN
2,Priya,28,65000,IT,6500.0,71500.0,young,NaN
3,Neha,35,90000,HR,9000.0,99000.0,30+,NaN
4,Vikram,24,45000,Finance,4500.0,49500.0,young,NaN